[package]
name = "index"
version = "1.0.0"
authors = [ "Anthony Riley <anthonyriley@stanford.edu>" ]
edition = "2018"

[dependencies]
http = "0.1"
image = "*"
vercel_lambda = "*"

[lib]
name = "contour"
path = "contour.rs"
